services:
  db:
    image: mysql:8.0
    container_name: crud-project-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: UnikaDevDB
      MYSQL_DATABASE: crud_project_db
    ports:
      - "3306:3306" # Mapeia a porta para o localhost do Windows
    volumes:
      - crud_project_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pUnikaDevDB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  crud_project_db_data:
    name: crud_project_db_data